#define SAMTOOLS_VERSION "1.19.2"
#define SAMTOOLS_CC "gcc"
#define SAMTOOLS_CPPFLAGS ""
#define SAMTOOLS_CFLAGS "-Wall -g -O2"
#define SAMTOOLS_LDFLAGS ""
#define SAMTOOLS_HTSDIR ""
#define SAMTOOLS_LIBS ""
#define SAMTOOLS_CURSES_LIB "-lncurses"
